version: "3.3"
services:
  demo-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_USERNAME=root
      - DB_PASSWORD=
      - PGDATABASE=demodb
      - PGHOST=postgres
    depends_on:
      - demodatabase
  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: demodb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
