version: "3.3"
services:
  demo-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "5555:5555"
    environment:
      - PORT=$PORT
      - NODE_ENV=$NODE_ENV
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - PGDATABASE=$PGDATABASE
      - PGHOST=$PGHOST
      - SYNC=$SYNC
    depends_on:
      - postgres
  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: demodb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
